import { ColumnDef } from "@tanstack/react-table"; // Certifique-se de instalar @tanstack/react-table
import { Expense } from "../../types/Expense";
import Cell from "./cell";

export const columns: ColumnDef<Expense>[] = [
	{
		id: "payer",
		accessorKey: "payer",
		header: "Pagador",
		meta: { type: "text" },
		cell: (info) => <Cell>{info.getValue() as string}</Cell>,
	},
	{
		id: "competenceDate",
		accessorKey: "competenceDate",
		header: "Competência",
		meta: { type: "date" },
		cell: (info) => <Cell>{info.getValue() as string}</Cell>,
	},
	{
		id: "dueDate",
		accessorKey: "dueDate",
		header: "Vencimento",
		meta: { type: "date" },
		cell: (info) => <Cell>{info.getValue() as string}</Cell>,
	},
	{
		id: "costCenter",
		accessorKey: "costCenter",
		header: "Centro de Custo",
		meta: { type: "select" },
		cell: (info) => <Cell>{info.getValue() as string}</Cell>,
	},
	{
		id: "category",
		accessorKey: "category",
		header: "Categoria",
		meta: { type: "select" },
		cell: (info) => <Cell>{info.getValue() as string}</Cell>,
	},
	{
		id: "paymentMethod",
		accessorKey: "paymentMethod",
		header: "Forma de Pagamento",
		meta: { type: "select" },
		cell: (info) => <Cell>{info.getValue() as string}</Cell>,
	},
	{
		id: "baseDocument",
		accessorKey: "baseDocument",
		header: "Base Documento",
		meta: { type: "text" },
		cell: (info) => <Cell>{info.getValue() as string}</Cell>,
	},
	{
		id: "account",
		accessorKey: "account",
		header: "Conta",
		meta: { type: "select" },
		cell: (info) => <Cell>{info.getValue() as string}</Cell>,
	},
	{
		id: "tax",
		accessorKey: "tax",
		header: "Taxa",
		meta: { type: "boolean" },
		cell: (info) => <Cell>{info.getValue() ? "Sim" : "Não"}</Cell>,
	},
	{
		id: "amount",
		accessorKey: "amount",
		header: "Valor",
		meta: { type: "number" },
		cell: (info) => <Cell>{info.getValue() as number}</Cell>,
	},
	{
		id: "description",
		accessorKey: "description",
		header: "Descrição",
		meta: { type: "text" },
		cell: (info) => <Cell>{info.getValue() as string}</Cell>,
	},
	{
		id: "observations",
		accessorKey: "observations",
		header: "Observações",
		meta: { type: "text" },
		cell: (info) => (
			<Cell className="min-w-[250px] truncate whitespace-nowrap overflow-hidden">
				{info.getValue() as string}
			</Cell>
		),
	},
	{
		id: "status",
		accessorKey: "status",
		header: "Situação",
		meta: { type: "select" },
		cell: (info) => <Cell>{info.getValue() as string}</Cell>,
	},
	{
		id: "paymentDate",
		accessorKey: "paymentDate",
		header: "Data de Pagamento",
		meta: { type: "date" },
		cell: (info) => <Cell>{info.getValue() as string}</Cell>,
	},
	{
		id: "paymentClearingDate",
		accessorKey: "paymentClearingDate",
		header: "Compensação de Pagamento",
		meta: { type: "date" },
		cell: (info) => <Cell>{info.getValue() as string}</Cell>,
	},
	{
		id: "discounts",
		accessorKey: "discounts",
		header: "Descontos",
		meta: { type: "number" },
		cell: (info) => <Cell>{info.getValue() as number}</Cell>,
	},
	{
		id: "addition",
		accessorKey: "addition",
		header: "Acréscimo",
		meta: { type: "number" },
		cell: (info) => <Cell>{info.getValue() as number}</Cell>,
	},
	{
		id: "totalPaid",
		accessorKey: "totalPaid",
		header: "Total Pago",
		meta: { type: "number" },
		cell: (info) => <Cell>{info.getValue() as number}</Cell>,
	},
	{
		id: "totalClearing",
		accessorKey: "totalClearing",
		header: "Valor Compensado",
		meta: { type: "number" },
		cell: (info) => <Cell>{info.getValue() as number}</Cell>,
	},
	{
		id: "installments",
		accessorKey: "installments",
		header: "Parcelas",
		meta: { type: "number" },
		cell: (info) => <Cell>{info.getValue() as number}</Cell>,
	},
	{
		id: "installmentType",
		accessorKey: "installmentType",
		header: "Tipo de Parcela",
		meta: { type: "select" },
		cell: (info) => <Cell>{info.getValue() as string}</Cell>,
	},
	{
		id: "itemPayer",
		accessorKey: "itemPayer",
		header: "Pagador do Item",
		meta: { type: "text" },
		cell: (info) => <Cell>{info.getValue() as string}</Cell>,
	},
	{
		id: "itemCategory",
		accessorKey: "itemCategory",
		header: "Categoria do Item",
		meta: { type: "select" },
		cell: (info) => <Cell>{info.getValue() as string}</Cell>,
	},
	{
		id: "itemCostCenter",
		accessorKey: "itemCostCenter",
		header: "Centro de Custo do Item",
		meta: { type: "select" },
		cell: (info) => <Cell>{info.getValue() as string}</Cell>,
	},
	{
		id: "itemBaseDocument",
		accessorKey: "itemBaseDocument",
		header: "Base Documento do Item",
		meta: { type: "text" },
		cell: (info) => <Cell>{info.getValue() as string}</Cell>,
	},
	{
		id: "itemDueDate",
		accessorKey: "itemDueDate",
		header: "Vencimento do Item",
		meta: { type: "date" },
		cell: (info) => <Cell>{info.getValue() as string}</Cell>,
	},
	{
		id: "itemDescription",
		accessorKey: "itemDescription",
		header: "Descrição do Item",
		meta: { type: "text" },
		cell: (info) => <Cell>{info.getValue() as string}</Cell>,
	},
	{
		id: "itemAmount",
		accessorKey: "itemAmount",
		header: "Valor do Item",
		meta: { type: "number" },
		cell: (info) => <Cell>{info.getValue() as number}</Cell>,
	},
	{
		id: "taxISS",
		accessorKey: "taxISS",
		header: "Taxa ISS",
		meta: { type: "number" },
		cell: (info) => <Cell>{info.getValue() as number}</Cell>,
	},
	{
		id: "taxCSSL",
		accessorKey: "taxCSSL",
		header: "Taxa CSSL",
		meta: { type: "number" },
		cell: (info) => <Cell>{info.getValue() as number}</Cell>,
	},
	{
		id: "taxPIS",
		accessorKey: "taxPIS",
		header: "Taxa PIS",
		meta: { type: "number" },
		cell: (info) => <Cell>{info.getValue() as number}</Cell>,
	},
	{
		id: "taxCONFINS",
		accessorKey: "taxCONFINS",
		header: "Taxa CONFINS",
		meta: { type: "number" },
		cell: (info) => <Cell>{info.getValue() as number}</Cell>,
	},
];
