import { Course } from ".";

export const FAKE_COURSES: Course[] = [
	{
		id: "1",
		category: "Desenvolvimento Web",
		name: "React Avançado",
		startDate: "2024-10-15",
		endDate: "2024-10-20",
		registrationDeadline: "2024-10-10",
		participantLimit: 30,
		instructors: "João Silva, Maria Oliveira",
		description:
			"Curso avançado de React com foco em performance e arquitetura.",
		permissions: "Acesso total",
		value: 1500,
		costCenter: "Desenvolvimento",
		billing: "Cartão de crédito",
		account: "Conta Principal",
		enrollment: "Online",
		paymentConfirmation: true,
		exemption: false,
		cancellation: false,
		inviteConfirmation: true,
		status: "Ativo",
	},
	{
		id: "2",
		category: "Marketing Digital",
		name: "SEO para Iniciantes",
		startDate: "2024-11-05",
		endDate: "2024-11-10",
		registrationDeadline: "2024-11-01",
		participantLimit: 50,
		instructors: "Ana Rodrigues",
		description:
			"Introdução às técnicas de SEO para melhorar o posicionamento em buscadores.",
		permissions: "Acesso limitado",
		value: 800,
		costCenter: "Marketing",
		billing: "Boleto bancário",
		account: "Conta de Marketing",
		enrollment: "Presencial",
		paymentConfirmation: false,
		exemption: true,
		cancellation: false,
		inviteConfirmation: true,
		status: "Pendente",
	},
];
