import { Submission } from ".";

export const FAKE_SUBMISSIONS: any[] = [
	{
		id: "sub-001",
		packagingName: "Nova Embalagem de Café",
		strategicPartners: "Café Brasileiro Ltda.",
		area: "Design de Embalagens",
		authors: "Carlos Pereira, Laura Gomes",
		institution: "Agência Criativa",
		date: "2024-09-20",
		event: "Feira de Design",
		submitedBy: "Carlos Pereira",
		packageReleaseDate: "2024-10-01",
		packageDesignAgency: "Agência Criativa",
		status: "Aprovado",
		presentationLink: "http://exemplo.com/apresentacao-cafe",
		comments: "Design inovador e sustentável.",
		number: 123,
		presentationDate: "2024-09-25",
		roomContent: "Sala Principal",
	},
	{
		id: "sub-002",
		packagingName: "Embalagem de Chocolate Premium",
		strategicPartners: "Chocolates Finos SA",
		area: "Design de Embalagens",
		authors: "Mariana Souza",
		institution: "Estúdio de Design",
		date: "2024-10-05",
		event: "Concurso de Embalagens",
		submitedBy: "Mariana Souza",
		packageReleaseDate: "2024-11-15",
		packageDesignAgency: "Estúdio de Design",
		status: "Em Análise",
		presentationLink: "http://exemplo.com/apresentacao-chocolate",
		comments: "Design elegante e sofisticado.",
		number: 456,
		presentationDate: "2024-10-10",
		roomContent: "Sala de Avaliação",
	},
];
