export type Customer = {
	id: string;
	name: string;
	email: string;
	customerType: string;
	cpf: string;
	cnpj: string;
	phone: string;
	mobile: string;
	userPassword: string;
	registrationDate: string;
	status: string;
	code: string;
	photo: string;
	zipCode: string;
	street: string;
	number: string;
	complement: string;
	neighborhood: string;
	state: string;
	city: string;
	corporateName: string;
	tradeName: string;
	billingEmail: string;
	billingName: string;
	billingPhone: string;
	billingMobile: string;
};

import { z } from "zod";
