import { ServiceDesk } from ".";

export const SERVICE_DESK_DATA: any[] = [
	{
		id: "1",
		registration: "reg-1",
		document: "doc-1",
		member: "member-1",
		phone: "123-456-7890",
		email: "user1@example.com",
		company: "Company 1",
		sector: "setor1",
		local: "local1",
		appointmentDate: "2025-04-01",
		appointmentHour: "10:00 AM",
		description: "Description for user 1",
	},
	{
		id: "2",
		registration: "reg-2",
		document: "doc-2",
		member: "member-2",
		phone: "123-456-7891",
		email: "user2@example.com",
		company: "Company 2",
		sector: "setor2",
		local: "local2",
		appointmentDate: "2025-04-02",
		appointmentHour: "10:01 AM",
		description: "Description for user 2",
	},
	{
		id: "3",
		registration: "reg-3",
		document: "doc-3",
		member: "member-3",
		phone: "123-456-7892",
		email: "user3@example.com",
		company: "Company 3",
		sector: "setor1",
		local: "local1",
		appointmentDate: "2025-04-03",
		appointmentHour: "10:02 AM",
		description: "Description for user 3",
	},
	{
		id: "4",
		registration: "reg-4",
		document: "doc-4",
		member: "member-4",
		phone: "123-456-7893",
		email: "user4@example.com",
		company: "Company 4",
		sector: "setor2",
		local: "local2",
		appointmentDate: "2025-04-04",
		appointmentHour: "10:03 AM",
		description: "Description for user 4",
	},
	{
		id: "5",
		registration: "reg-5",
		document: "doc-5",
		member: "member-5",
		phone: "123-456-7894",
		email: "user5@example.com",
		company: "Company 5",
		sector: "setor1",
		local: "local1",
		appointmentDate: "2025-04-05",
		appointmentHour: "10:04 AM",
		description: "Description for user 5",
	},
	{
		id: "6",
		registration: "reg-6",
		document: "doc-6",
		member: "member-6",
		phone: "123-456-7895",
		email: "user6@example.com",
		company: "Company 6",
		sector: "setor2",
		local: "local2",
		appointmentDate: "2025-04-06",
		appointmentHour: "10:05 AM",
		description: "Description for user 6",
	},
	{
		id: "7",
		registration: "reg-7",
		document: "doc-7",
		member: "member-7",
		phone: "123-456-7896",
		email: "user7@example.com",
		company: "Company 7",
		sector: "setor1",
		local: "local1",
		appointmentDate: "2025-04-07",
		appointmentHour: "10:06 AM",
		description: "Description for user 7",
	},
	{
		id: "8",
		registration: "reg-8",
		document: "doc-8",
		member: "member-8",
		phone: "123-456-7897",
		email: "user8@example.com",
		company: "Company 8",
		sector: "setor2",
		local: "local2",
		appointmentDate: "2025-04-08",
		appointmentHour: "10:07 AM",
		description: "Description for user 8",
	},
	{
		id: "9",
		registration: "reg-9",
		document: "doc-9",
		member: "member-9",
		phone: "123-456-7898",
		email: "user9@example.com",
		company: "Company 9",
		sector: "setor1",
		local: "local1",
		appointmentDate: "2025-04-09",
		appointmentHour: "10:08 AM",
		description: "Description for user 9",
	},
	{
		id: "10",
		registration: "reg-10",
		document: "doc-10",
		member: "member-10",
		phone: "123-456-7899",
		email: "user10@example.com",
		company: "Company 10",
		sector: "setor2",
		local: "local2",
		appointmentDate: "2025-04-10",
		appointmentHour: "10:09 AM",
		description: "Description for user 10",
	},
];
